<?php

namespace AppBundle\Repository;

/**
 * CartItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
