<?php

namespace AppBundle\Repository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIndexProducts($max = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb
            ->select('p')
            ->from('AppBundle:Product','p');

        if(!is_null($max)){
            $qb->setMaxResults($max);
        }

        try{
            return $qb->getQuery()->getResult();
        }catch (\Exception $ex){
            return null;
        }
    }
}
