<?php

namespace AppBundle\Repository;

/**
 * ProfessionalOrieantionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionalOrieantionRepository extends \Doctrine\ORM\EntityRepository
{
}
